local_costmap:
  update_frequency: 15.0
  publish_frequency: 5.0
  always_send_full_costmap: true
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.1

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      {
        sensor_frame: laser,  # vorher laser_link
        data_type: LaserScan,
        topic: /scan,         # vorher /laser/scan
        clearing: true,
        marking: true,
      }
    max_obstacle_height: 3
    obstacle_range: 10
    raytrace_range: 11

  inflater_layer:
    inflation_radius: 0.05
    cost_scaling_factor: 0.1

  plugins:
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflater_layer, type: "costmap_2d::InflationLayer" }
